Feature/header
pawelrogowski/goit-wallet-app-03-frontend pull request #14
Opened 2023-07-18 15:31 UTC by rafalszewczyk890

Header done

2023-07-18 15:32 UTC, rafalszewczyk890 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Header](https://trello.com/c/d2mG0E3Y/16-header)

2023-07-18 17:32 UTC, rafalszewczyk890 commented
Buttony dodane

2023-07-18 18:48 UTC, pawelrogowski requested changes

2023-07-18 18:48 UTC, pawelrogowski commented on src/components/Header/Header.jsx
> +        <button className="exitButton">
brak type="button" w buttonach, wiem że pierdoła ale skoro wszystko idzie przez pull requesty to proszę o poprawkę bo nie chce wysyłać commita prosto w dev
dorzucam info odnośnie type
![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/5f449ae0-f5a2-495b-9e88-402a39470a08)

2023-07-19 07:13 UTC, rafalszewczyk890 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Header](https://trello.com/c/d2mG0E3Y/16-header)

2023-07-19 12:52 UTC, pawelrogowski commented
dorzuciłem trochę styli na hover/focus, zapomniałem o tym dodac przy poprzednim review, leci merge

2023-07-19 12:52 UTC, pawelrogowski approved these changes

2023-07-19 12:52 UTC, merged