Statistic page
pawelrogowski/goit-wallet-app-03-frontend pull request #29
Opened 2023-07-21 18:12 UTC by gash94

2023-07-21 23:58 UTC, pawelrogowski commented
Brakuje s
![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/9ce8191e-7300-4155-8a08-f8a50aac9327)

Balance jest za wysokie - powinnoo mieć na sztywno 80px
![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/1b962351-74df-4a8f-9442-ae1e5ffff14e)

Brak hovera/focus na dropdownie 
![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/8d465443-f4ae-4e71-8fac-c2fbc7739572)
![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/68ed9594-d3bd-4c57-bc55-bbc7028b5829)

Migający kursor po wybraniu dropdown i zbyt duży height - powinno byc 50px
![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/bde4e846-70a4-4d0c-9c55-a2cfa0378312)

Tablet: lista nie schodzi do prawej tak jak powinna i paddingi kontenera nie zgadzają się z figmą
![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/2d8e0029-ef33-4d1c-97a3-5bf57f61fc7f)

Brak Scrollbarów jeśli jest overflow na Y

Mobile:
![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/073d6e7a-f676-4946-b3e8-51bedcd374a4)

brak scrollbarów / możliwości przewijania contentu - gdzieś w kodzie musi być overflow-y schowany bo nadpisując go włącza scrollbar


Masa źle zastosowanych marginów i paddingów, stosujcie się do tego że padding wpychają zawartośc w kontener, a marginy odpychają element od innych elementów w kontenerze, a najlepiej użyć gap w flexboxie jeśli mają ten sam kontener

![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/eb5f0222-8151-4361-873e-e27ae31d7ea8)

background był źle zainplementowany w index.js - jest fixed elementem z z-indexem żeby być pod spodem wszędzie 
po poprawce w index js żeby nie wrapował app a był obok w dom i dodaniu scrollbara są sytuacje gdzie background z kontenerów się ucina
![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/5e12d94d-e35c-4d22-ad7c-957409d8a473)

2023-07-22 20:13 UTC, pawelrogowski requested changes
1. line-height: 18px ustawić na każdy p w liście, padding góra dół na 14px i się element listy zgadza z figmą
2. to samo income i expenses
3. pozbyć się minusowych marginów
![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/91047875-94db-4bba-a155-5b4860fc94d1)
4. nie używać stałego width dla elementu z dropdownem, ustawić na 100% i manipulować gapem w flexboxie 
![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/26950f72-cb9c-4e98-99e1-9b6c4be338b3)
5. kontener ma 1 ustawienie paddingu na każdy brakpoint i wystarczy, rozmieszczenie przedmiotów w środku kontenera flexboxem. Rozmieszczenie elementów w środku mniejszych boxów też flexem, marginu używać tylko jeśli odpychasz elementy od siebie w tym samym kontenerze (przykładowo masz 5 elementów w liście z czego między 4 a 5 jest nieregularna przerwa, wtedy w css po Ntym elemencie dodać margin), w całym layoucie nie ma powodu żeby marginu używać
a skoro umawialiśmy się na flexbox to egzekwuje

Używaj Wcięć (Padding): Wcięcia są przydatne do tworzenia odstępów między zawartością a krawędziami kontenera. Często są stosowane do dodawania przestrzeni wewnątrz kontenera, oddzielając zawartość od krawędzi. Poprzez dostosowywanie wartości wcięć w kontenerze, kontrolujesz odstępy między zawartością a jego krawędziami.

Wykorzystaj Odstępy Flexbox (Flexbox Gaps): Odstępy flexbox (nazywane także przestrzenią flexbox) pozwalają na tworzenie odstępów między elementami flexbox (komponentami) wewnątrz kontenera. Stanowią one doskonałą alternatywę dla stosowania marginesów między elementami flexbox, ponieważ upraszczają układ i eliminują potencjalne problemy z marginesami.

Unikaj Używania Marginesów do Odstępów Między Elementami Flexbox: Choć teoretycznie można stosować marginesy w elementach flexbox, zazwyczaj lepiej polegać na odstępach flexbox i wcięciach do odstępów między elementami. Użycie marginesów w elementach flexbox może czasem prowadzić do nieoczekiwanego zachowania, zwłaszcza w przypadku zagnieżdżonych kontenerów flexbox.

Rozważ Wykorzystanie Zagnieżdżonych Kontenerów Flexbox: Jeśli masz bardziej złożony układ, w którym potrzebujesz różnych odstępów między grupami elementów flexbox, rozważ użycie zagnieżdżonych kontenerów flexbox. Pozwala to na stosowanie różnych odstępów flexbox i wcięć na różnych poziomach hierarchii układu.

Pamiętaj o Właściwościach Flexbox: Oprócz odstępów flexbox, masz do dyspozycji inne potężne właściwości flexbox, takie jak justify-content, align-items, align-self i flex, które pozwalają kontrolować układ i odstępy między elementami flexbox. Zapoznaj się z tymi właściwościami, aby tworzyć elastyczne i responsywne projekty.

Projektowanie Responsywne: Wykorzystaj media queries do dostosowywania wcięć, odstępów flexbox i innych właściwości flexbox na podstawie rozmiaru ekranu lub rodzaju urządzenia. Zapewni to, że układ będzie dobrze dostosowany do różnych widoków.

2023-07-23 08:30 UTC, DawidBartus commented
Aside poprawione. 
Trzeba poprawić Navigation. bo nie ma zrobionych gap'ów między elementami i wydaje mi się że dlatego się się w aside układa lewa część. Chyba że to jest już poprawione, tylko że pracuję na statistic-page więc zmiany nie są wprowadzone.

2023-07-23 18:59 UTC, pawelrogowski approved these changes
zmiany wprowadzone, póki co nie mam uwag, fix na aside kończyć na osobnym branchu
leci merge

2023-07-23 18:59 UTC, merged