Add ModalLogout open
pawelrogowski/goit-wallet-app-03-frontend pull request #32
Opened 2023-07-22 09:06 UTC by Wiktoritho

2023-07-22 13:07 UTC, pawelrogowski requested changes
modal proszę przesunąć ze środka strony bliżej górnej krawędzi ekranu, tak aby nie pojawiał się kilometry od przycisku który go włącza

2023-07-22 13:13 UTC, pawelrogowski requested changes
dorzucić z-index żeby takie sytuacje nie miały miejsca
![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/db5268da-0e44-4c60-9888-b70dbf290b61)

2023-07-24 13:34 UTC, Wiktoritho commented
Fixed bugs in feature/ModalLogout

2023-07-24 13:50 UTC, pawelrogowski approved these changes
Merguje żeby już był, potem się go ewentualnie ruszy bliżej headera i przycisku logout/zmieni treść i kolor buttonów

zeby jasno było to w poprzednim review chodziło mi o to żeby NO było domyślnie podświetlone 
![image](https://github.com/pawelrogowski/goit-wallet-app-03-frontend/assets/110867327/6f89cdf5-8d9b-4fd8-9a16-8f4c04ba3547)

2023-07-24 14:04 UTC, merged